Update secret-detection.yml

diff --git a/.github/workflows/secret-detection.yml b/.github/workflows/secret-detection.yml
--- a/.github/workflows/secret-detection.yml
+++ b/.github/workflows/secret-detection.yml
@@ -38,14 +38,20 @@ jobs:
         run: |          
           chown -R $(id -u):$(id -g) $PWD
 
-      # Delete .secrets.baseline
-      - name: Delete local .secrets.baseline
-        run: |          
-          rm .secrets.baseline
-
       # Run Yelp
       - name: Scan detect-secrets with Yelp
-        uses: RobertFischer/detect-secrets-action@v2.0.0         
+        id: detect-secrets
+        uses: RobertFischer/detect-secrets-action@v2.0.0      
+
+      - name: View Result
+        run: |
+          cat ${{ steps.detect-secrets.DS_ADDL_ARGS }}        
+          cat ${{ steps.detect-secrets.DS_BASELINE_FILE }}
+          lines='echo $output | jq .results | wc -l'
+          if [ "$lines" -gt 1 ]; then
+            echo "Secret Check Failed"
+            exit 1
+          fi
 
       # Commit .secrets.baseline
       - name: Commit back .secrets.baseline (if it was missing)
